### ISSUE TITLE
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### ISSUE THREAD

**Issue by AndreasAZiegler** [ferdium/ferdium-app#1085]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4-1

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 6.2.8-arch1-1

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.4-1

### Expected Behavior

Ferdium starting smoothly.

### Actual Behavior

After a recent updated of the Nvidia GPU driver, I get the following error.
```
ferdium
SyntaxError: /home/ziegler/.config/Ferdium/config/settings.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileSync (/opt/ferdium-bin/resources/app.asar/node_modules/jsonfile/index.js:52:17)
    at n._hydrate (/opt/ferdium-bin/resources/app.asar/electron/Settings.js:1:1314)
    at new Settings (/opt/ferdium-bin/resources/app.asar/electron/Settings.js:1:1031)
    at Object.<anonymous> (/opt/ferdium-bin/resources/app.asar/index.js:1:2082)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

### Steps to reproduce

1. Start ferdium in terminal with `ferdium`.

**Comment by marie-bnl** [comment]
Can you send your `~/.config/Ferdium/config/settings.json` file?

**Comment by AndreasAZiegler** [comment]
`~/config/Ferdium/config/settings.json` exists but is empty.

**Comment by marie-bnl** [comment]
It’s strange that your settings file got empty. Write into the file:

```
{}
```

And start Ferdium again

**Comment by AndreasAZiegler** [comment]
Now I get the following:
```
ferdium
SyntaxError: /home/ziegler/.config/Ferdium/config/proxy.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileSync (/opt/ferdium-bin/resources/app.asar/node_modules/jsonfile/index.js:52:17)
    at n._hydrate (/opt/ferdium-bin/resources/app.asar/electron/Settings.js:1:1314)
    at new Settings (/opt/ferdium-bin/resources/app.asar/electron/Settings.js:1:1031)
    at Object.<anonymous> (/opt/ferdium-bin/resources/app.asar/index.js:1:2135)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
[3704235:0423/162005.664730:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3704235:0423/162005.665513:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[3704441:0423/162010.833858:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
With `set -x LIBVA_DRIVER_NAME vdpau`, I get
```
ferdium
SyntaxError: /home/ziegler/.config/Ferdium/config/proxy.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileSync (/opt/ferdium-bin/resources/app.asar/node_modules/jsonfile/index.js:52:17)
    at n._hydrate (/opt/ferdium-bin/resources/app.asar/electron/Settings.js:1:1314)
    at new Settings (/opt/ferdium-bin/resources/app.asar/electron/Settings.js:1:1031)
    at Object.<anonymous> (/opt/ferdium-bin/resources/app.asar/index.js:1:2135)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
[3706647:0423/162117.274941:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3706647:0423/162117.275091:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3706850:0423/162123.260130:ERROR:vaapi_wrapper.cc(1315)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[3706850:0423/162123.260221:ERROR:vaapi_wrapper.cc(1262)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[3706850:0423/162123.260249:ERROR:vaapi_wrapper.cc(1315)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[3706850:0423/162123.260275:ERROR:vaapi_wrapper.cc(1262)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
[3706850:0423/162123.302094:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[3707078:0423/162127.114977:ERROR:vaapi_wrapper.cc(1315)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[3707078:0423/162127.115110:ERROR:vaapi_wrapper.cc(1262)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[3707078:0423/162127.115232:ERROR:vaapi_wrapper.cc(1315)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[3707078:0423/162127.115312:ERROR:vaapi_wrapper.cc(1262)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
```

**Comment by AndreasAZiegler** [comment]
After also adding a `{}` to `~/config/Ferdium/config/proxy.json`, Ferdium starts again.

**Comment by marie-bnl** [comment]
At this stage I’d have deleted the Ferdium directory to start anew! But I’m glad you got it working back
