### ISSUE TITLE
Todo Sidebar not resizable

### ISSUE THREAD

**Issue by RaphaelJenni** [ferdium/ferdium-app#1107]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6

### What Operating System are you using?

Ubuntu

### Operating System Version

22.10

### What arch are you using?

x64

### Expected Behavior

The todo drawer on the right side is resizable when hovering over the border.	

### Actual Behavior

The cursor changes to the resize functionality but does noting.	

### Steps to reproduce

1. Open the todo drawer
2. Try to resize (change width)

### Additional information

Not only on Ubuntu. Same problem on Windows.

**Comment by RaphaelJenni** [comment]
Error when clicking on the resize bar:
```
/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4091 Uncaught TypeError: Cannot read properties of undefined (reading 'setState')
    at startResize (/app/Ferdium/resources/app.asar/features/todos/components/TodosWebview.js:1:2346)
    at HTMLUnknownElement.callCallback (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at invokeGuardedCallbackAndCatchFirstError (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4070:25)
    at executeDispatch (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8243:3)
    at processDispatchQueueItemsInOrder (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8275:7)
    at processDispatchQueue (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8288:5)
    at dispatchEventsForPlugins (/app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8299:3)
    at /app/Ferdium/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8508:12
```
