### ISSUE TITLE
Release 6.2.7: hashsum mismatch for Ferdium-linux-Portable-6.2.7-x86_64.AppImage

### ISSUE THREAD

**Issue by TwizzyDizzy** [ferdium/ferdium-app#1159]
### Your issue

Reproduce: 
* use your current version `Ferdium-linux-Portable-6.2.6-x86_64.AppImage`
* try auto update in settings
* wait for error on Ferdium console (see below)

```
Error: sha512 checksum mismatch, expected yjcqwUQTH1d04GbVnKhNAbGJI+m/8Iw5WcrSXK/OxdcUQ0lMO6asPvSpR7x3yaJfXd2Z8yNDVAAEC8qAMY/vhQ==, got KVLP+AZ13RCnqTU+yB2/ikI13unOv/0veXPjZrL7vJ7EiiZ5rPBcHPvvPb3c/yh1D1mVeopkJbud52V7FOvq+w==
    at Object.newError (/tmp/.mount_ferdiu5w4qsz/resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
    at DigestTransform.validate (/tmp/.mount_ferdiu5w4qsz/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:352:27)
    at DigestTransform._flush (/tmp/.mount_ferdiu5w4qsz/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:338:22)
    at DigestTransform.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at Writable.end (node:internal/streams/writable:634:5)
    at ProgressCallbackTransform.onend (node:internal/streams/readable:705:10)
    at Object.onceWrapper (node:events:627:28)
    at ProgressCallbackTransform.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_CHECKSUM_MISMATCH'
```

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
As confirmed and pointed out by @Alphrag [on Discord](https://discord.com/channels/963836780778512454/963841911376982046/1108048343680176128): seems to have been a one-time fluke (maybe race condition) in the build process.

Closing here.

Cheers
Thomas
