### ISSUE TITLE
[Broken Recipe] New Snapchat Web requires browser login.

### ISSUE THREAD

**Issue by jeremymeyers** [ferdium/ferdium-app#1372]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1

### Recipe Name

SnapChat

### Recipe Version

1.2

### Steps to reproduce

1. Load Snapchat service
2. Click "log into chat"

### Expected Behavior

Login window is shown within ferdium, allowing login/session capture.

### Actual Behavior

Clicking "log in" opens a login window in a web browser, user session does not transfer over to ferdium.

### Additional Information

This happens regardless of whether "Open URLs in Ferdium" is checked in the service config menu.

**Comment by SpecialAro** [comment]
Hi @jeremymeyers have you tried to right click and click on Open link in Ferdium?

**Comment by jeremymeyers** [comment]
that option doesn't show up for me. I'm on a Mac, dunno if that makes a difference On Sep 23, 2023 11:22 AM, André Oliveira ***@***.***> wrote:
Hi @jeremymeyers have you tried to right click and click on Open link in Ferdium?

**Comment by fragment137** [comment]
I can confirm this is happening in MacOS version 13.5.2, Ferdium Version: 6.4.1
Behaviour is exactly as outlined above. I also do not see the "Open link in Ferdium" option when right clicking on the Log in to Chat button.
<img width="523" alt="image" src="https://github.com/ferdium/ferdium-app/assets/63161053/bff2e939-a424-4174-ae03-71fb33c203fb">

**Comment by beck** [comment]
If you right-click the service icon and click "edit", there is an option "Open URLs within Ferdium":

<img width="325" alt="image" src="https://github.com/ferdium/ferdium-app/assets/154988/cd8c9dd5-9d9a-4a89-ad1c-6b81c4b8524e">

This worked for me.

**Comment by fragment137** [comment]
Unfortunately this did not work for me. I confirmed I had this setting
enabled.

**Comment by beck** [comment]
Yeah, on a different computer getting the same issue (even with this setting enabled). IDK if relevant but console has error:

> electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'get-dnd': Error: ENOTDIR: not a directory, stat '/Applications/Ferdium.app/Contents/Resources/app.asar/electron/ipc-api/node_modules/macos-notification-state'
>     at a.invoke (node:electron/js2c/renderer_init:2:7723)
>     at async i._systemDND (/Applications/Ferdium.app/Contents/Resources/app.asar/stores/AppStore.js:1:11797)

Extra weird though (and maybe snapchat is running an experiment) refreshing a handful of times, I was able to eventually get a login page 🤷‍♂️

**Comment by jeremymeyers** [comment]
This is still not working for me.

**Comment by Roan-V** [comment]
> Yeah, on a different computer getting the same issue (even with this setting enabled). IDK if relevant but console has error:
> 
> > electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'get-dnd': Error: ENOTDIR: not a directory, stat '/Applications/Ferdium.app/Contents/Resources/app.asar/electron/ipc-api/node_modules/macos-notification-state'
> > at a.invoke (node:electron/js2c/renderer_init:2:7723)
> > at async i._systemDND (/Applications/Ferdium.app/Contents/Resources/app.asar/stores/AppStore.js:1:11797)
> 
> Extra weird though (and maybe snapchat is running an experiment) refreshing a handful of times, I was able to eventually get a login page 🤷‍♂️

Can confirm, after refreshing a few times I managed to get the login screen as well
I did also enable "Open URLs within Ferdium"
