### ISSUE TITLE
Purple Screen of death - after update, but neither deleting profile nor downgrading helps...

### ISSUE THREAD

**Issue by n00b42** [ferdium/ferdium-app#1731]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.2

### Expected Behavior

no purple screen

### Actual Behavior

purple screen

### Steps to reproduce

- After updating to 6.7.3 Ferdium app was stuck in a purple screen.
- First, I tried resetting my profile (deleting AppData/Roaming/Ferdium) -> Asks for login, press "without account" -> Still purple screen
- Then tried downgrading to 6.7.2 -> Still purple screen

No error no information...

Tried downgrading to 6.7.1 as well, tried upgrading again, deleted profile multiple times, restarted PC, ...
Started from Cmd -> not useful error output...

Any suggestions?

### Screenshots

![grafik](https://github.com/ferdium/ferdium-app/assets/6792900/440a34c3-7a93-463f-923b-5018649fd91b)
![grafik](https://github.com/ferdium/ferdium-app/assets/6792900/152e5449-3cb1-4751-95a1-22f7a32b2c67)

**Comment by SpecialAro** [comment]
Can you please try to open the developer console (CTRL+ALT+I) and paste the output here?

**Comment by n00b42** [comment]
Tried to enter der developer console, but neither in the account creation/skip dialogue nor in the purple screen something happened.

**Comment by n00b42** [comment]
Without existing profile
![Ferdium_yOCnlu43fC](https://github.com/ferdium/ferdium-app/assets/6792900/91de46ca-a972-46db-a850-9862d6886923)
With existing (empty) profile
![Ferdium_VziHCrNOJA](https://github.com/ferdium/ferdium-app/assets/6792900/a602a685-59d5-4fff-8173-46d6caf72e7a)

**Comment by n00b42** [comment]
for whatever reason, the UI showed one time, but could not reproduce, then another test I was able to bring up the console now...

~~~
C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:29840
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[_firstLaunchReaction]
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "menu.view.openProcessManager" for locale "de", using default message (Open Process Manager) as fallback.

    at new MissingTranslationError (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:13421)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "global.downloads" for locale "de", using default message (Downloads) as fallback.

    at new MissingTranslationError (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:15551)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound _build]' Error: Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
    at makeError (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at module.exports.sync (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\index.js:188:17)
    at windowsRelease (C:\Program Files\Ferdium\resources\app.asar\node_modules\windows-release\index.js:39:19)
    at osName (C:\Program Files\Ferdium\resources\app.asar\node_modules\os-name\index.js:43:18)
    at I.getOsName (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12324)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:16620)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1 Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "menu.view.openProcessManager" for locale "de", using default message (Open Process Manager) as fallback.

    at new MissingTranslationError (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:13421)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "global.downloads" for locale "de", using default message (Downloads) as fallback.

    at new MissingTranslationError (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:15551)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound _build]' Error: Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
    at makeError (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at module.exports.sync (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\index.js:188:17)
    at windowsRelease (C:\Program Files\Ferdium\resources\app.asar\node_modules\windows-release\index.js:39:19)
    at osName (C:\Program Files\Ferdium\resources\app.asar\node_modules\os-name\index.js:43:18)
    at I.getOsName (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12324)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:16620)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "menu.view.openProcessManager" for locale "de", using default message (Open Process Manager) as fallback.

    at new MissingTranslationError (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:13421)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "global.downloads" for locale "de", using default message (Downloads) as fallback.

    at new MissingTranslationError (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:15551)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound _build]' Error: Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
    at makeError (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at module.exports.sync (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\index.js:188:17)
    at windowsRelease (C:\Program Files\Ferdium\resources\app.asar\node_modules\windows-release\index.js:39:19)
    at osName (C:\Program Files\Ferdium\resources\app.asar\node_modules\os-name\index.js:43:18)
    at I.getOsName (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12324)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:16620)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1808
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: UserStore@28.authToken
checkIfStateModificationsAreAllowed @ C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1808

C:\Program Files\Ferdium\resources\app.asar\node_modules\tiny-warning\dist\tiny-warning.cjs.js:13
Warning: [JSS] <inject-with-stores(LoaderComponent) />'s styles function doesn't rely on the "theme" argument. We recommend declaring styles as an object instead.
warning @ C:\Program Files\Ferdium\resources\app.asar\node_modules\tiny-warning\dist\tiny-warning.cjs.js:13
localhost:46569/v1/me/newtoken:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
localhost:46569/v1/features:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22839
Uncaught Error: Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
    at makeError (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at module.exports.sync (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\index.js:188:17)
    at windowsRelease (C:\Program Files\Ferdium\resources\app.asar\node_modules\windows-release\index.js:39:19)
    at osName (C:\Program Files\Ferdium\resources\app.asar\node_modules\os-name\index.js:43:18)
    at I.getOsName (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12324)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:16620)
    at I.rebuild (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12138)
    at a.componentDidUpdate (C:\Program Files\Ferdium\resources\app.asar\I18n.js:1:1102)
    at commitLayoutEffectOnFiber (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23338:28)
    at commitLayoutMountEffects_complete (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24688:9)

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
The above error occurred in the <I18N> component:

    at I18N (C:\Program Files\Ferdium\resources\app.asar\I18n.js:1:1030)
    at C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx-react\dist\mobxreact.cjs.development.js:524:34
    at Provider (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx-react\dist\mobxreact.cjs.development.js:493:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1

C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12056
Uncaught Error: Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
    at makeError (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at module.exports.sync (C:\Program Files\Ferdium\resources\app.asar\node_modules\execa\index.js:188:17)
    at windowsRelease (C:\Program Files\Ferdium\resources\app.asar\node_modules\windows-release\index.js:39:19)
    at osName (C:\Program Files\Ferdium\resources\app.asar\node_modules\os-name\index.js:43:18)
    at I.getOsName (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12324)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:16620)
    at I.rebuild (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12138)
    at a.componentDidUpdate (C:\Program Files\Ferdium\resources\app.asar\I18n.js:1:1102)
    at commitLayoutEffectOnFiber (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23338:28)
    at commitLayoutMountEffects_complete (C:\Program Files\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24688:9)

C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound _build]' TypeError: Cannot read properties of null (reading 'formatMessage')
    at I.serviceTpl (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:18315)
    at I._build (C:\Program Files\Ferdium\resources\app.asar\lib\Menu.js:1:12406)
    at reactionRunner (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2634:5)
    at trackDerivedFunction (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1839:18)
    at Reaction.track (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2354:18)
    at Reaction.onInvalidate_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2615:12)
    at Reaction.runReaction_ (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2319:16)
    at runReactionsHelper (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2472:29)
    at reactionScheduler (C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2448:10)
    at C:\Program Files\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2482:14
window.console.error @ C:\Program Files\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1
~~~

**Comment by SpecialAro** [comment]
Hummm... it looks like it's missing some DE translations, and that maybe makes it crash

**Comment by n00b42** [comment]
Probably related to https://github.com/ferdium/ferdium-app/issues/1346 ?

**Comment by n00b42** [comment]
So, adding powershell folder to the path variable fixes the issue for me.
However, it should not be required to manually edit the path to run Ferdium...

**Comment by SpecialAro** [comment]
> So, adding powershell folder to the path variable fixes the issue for me. However, it should not be required to manually edit the path to run Ferdium...

This is weird. How are you running Ferdium and how did if solve it exactly?

**Comment by n00b42** [comment]
- I installed Ferdium using "AutoSetup x64 exe" from https://ferdium.org/download
- Then just started it from the Windows Startmenu (or Autostarted later on)

Fixed it by adding `C:\Windows\System32\WindowsPowerShell\v1.0` to both user PATH as well as system PATH environment variable (as suggested here: https://github.com/ferdium/ferdium-app/issues/1346#issuecomment-1801223151)
