### ISSUE TITLE
Teams notifications don't auto-dismiss on windows

### ISSUE THREAD

**Issue by CoreParadox** [ferdium/ferdium-app#1867]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.6-nightly.8

### Recipe Name

Microsoft Teams

### Recipe Version

3.3.2

### Steps to reproduce

1. Setup a MS Teams service
2. Receive a notification on Windows 11
3. The notification will stay on screen until manually dismissed	

### Expected Behavior

When receiving a notification it should automatically hide after a short period of time

### Actual Behavior

The notification will not hide until manually closed or swiped away, and will stack up to 3 visible, and a seemingly infinite backlog.

### Screenshots

Expected:
https://github.com/user-attachments/assets/23653ff7-c000-4c5c-b37c-a9563b88534d

Actual:
https://github.com/user-attachments/assets/4f597953-d442-4b89-9d7f-cae89c49d8d0

### Additional Information

I have not seen this happen with other recipes, such as discord, obviously not an extensive list.

**Comment by EdgardoSchiffer** [comment]
+1 the same behaviour is present on Garuda Linux KDE, Teams notifications does not auto-dismiss on v6.7.6

**Comment by marrws** [comment]
Experiencing the same in Xubuntu 24.04

### Debug information

```json
{"host":{"platform":"linux","release":"6.8.0-41-generic","screens":[{"accelerometerSupport":"unknown","bounds":{"x":1920,"y":0,"width":2560,"height":1440},"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"detected":true,"displayFrequency":59.9505500793457,"id":2,"internal":false,"label":"DELL S2721DS","maximumCursorSize":{"width":0,"height":0},"monochrome":false,"nativeOrigin":{"x":1920,"y":0},"rotation":0,"scaleFactor":1,"size":{"width":2560,"height":1440},"workArea":{"x":1920,"y":27,"width":2560,"height":1390},"workAreaSize":{"width":2560,"height":1390},"touchSupport":"unknown"},{"accelerometerSupport":"unknown","bounds":{"x":0,"y":0,"width":1920,"height":1080},"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"detected":true,"displayFrequency":60.02674865722656,"id":5,"internal":true,"label":"Pantalla integrada","maximumCursorSize":{"width":0,"height":0},"monochrome":false,"nativeOrigin":{"x":0,"y":0},"rotation":0,"scaleFactor":1,"size":{"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1080},"touchSupport":"unknown"}]},"ferdium":{"version":"6.7.6","electron":"31.3.1","installedRecipes":[{"id":"discord","version":"1.8.1"},{"id":"franz-custom-website","version":"1.5.1"},{"id":"instagram","version":"2.5.4"},{"id":"instagram-direct-messages","version":"1.1.3"},{"id":"jira","version":"1.5.1"},{"id":"msteams","version":"3.3.2"},{"id":"office365-owa","version":"1.7.3"},{"id":"slack","version":"1.6.2"},{"id":"twitter","version":"1.4.2"},{"id":"whatsapp","version":"3.5.7"},{"id":"workplace","version":"1.4.0"},{"id":"yammer","version":"1.3.1"},{}],"devRecipes":[],"services":[{"id":"a745971f-e49b-485a-8b1f-32de5140c835","recipe":"office365-owa","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"e442de8f-8c81-4941-b5f8-9257e0ff3fa2","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"a5721fb8-bcd5-4882-ba75-2a6f622c62c3","recipe":"msteams","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"d9d1eb34-5e6f-4d48-b7fc-000d8070c8ec","recipe":"jira","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":true},{"id":"b4d533c8-2557-4704-ba19-ad7b7bb4b543","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"c8f4f2ac-6299-4f95-a8c5-9f4c482c1eb4","recipe":"yammer","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false}],"messages":[{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"menu.view.openProcessManager","defaultMessage":"Open Process Manager"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"menu.view.openProcessManager","defaultMessage":"Open Process Manager"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error","Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node%s","\n    at WithSortableContainer (/opt/Ferdium/resources/app.asar/node_modules/react-sortable-hoc/dist/react-sortable-hoc.js:614:7)\n    at div\n    at TabBar (/opt/Ferdium/resources/app.asar/components/services/tabs/Tabbar.js:1:1123)\n    at div\n    at Sidebar (/opt/Ferdium/resources/app.asar/components/layout/Sidebar.js:1:2222)\n    at /opt/Ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at injectIntl(inject-with-stores-actions(Sidebar))\n    at div\n    at div\n    at ErrorBoundary (/opt/Ferdium/resources/app.asar/components/util/ErrorBoundary/index.js:1:1286)\n    at injectIntl(ErrorBoundary)\n    at /opt/Ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at AppLayout (/opt/Ferdium/resources/app.asar/components/layout/AppLayout.js:1:2936)\n    at /opt/Ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/opt/Ferdium/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/opt/Ferdium/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1494)\n    at /opt/Ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at RenderedRoute (/opt/Ferdium/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:539:7)\n    at Routes (/opt/Ferdium/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1229:7)\n    at Router (/opt/Ferdium/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1163:17)\n    at HistoryRouter (/opt/Ferdium/resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:770:7)\n    at FerdiumRoutes (/opt/Ferdium/resources/app.asar/routes.js:1:2693)\n    at /opt/Ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/opt/Ferdium/resources/app.asar/node_modules/react-intl/src/components/provider.js:33:47)\n    at I18N (/opt/Ferdium/resources/app.asar/I18n.js:1:1030)\n    at /opt/Ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/opt/Ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"menu.view.openProcessManager","defaultMessage":"Open Process Manager"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"menu.view.openProcessManager","defaultMessage":"Open Process Manager"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.clearCache","defaultMessage":"Clear cache"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.clearCache","defaultMessage":"Clear cache"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.clearCache","defaultMessage":"Clear cache"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.clearCache","defaultMessage":"Clear cache"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.clearCache","defaultMessage":"Clear cache"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.clearCache","defaultMessage":"Clear cache"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"menu.view.openProcessManager","defaultMessage":"Open Process Manager"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"code":"MISSING_TRANSLATION","descriptor":{"id":"global.downloads","defaultMessage":"Downloads"}}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"}],"workspaces":[{"id":"3df5ac2a-fb90-4588-9e4d-5381cfe71a71","services":["a745971f-e49b-485a-8b1f-32de5140c835","a5721fb8-bcd5-4882-ba75-2a6f622c62c3","b4d533c8-2557-4704-ba19-ad7b7bb4b543","e442de8f-8c81-4941-b5f8-9257e0ff3fa2","d9d1eb34-5e6f-4d48-b7fc-000d8070c8ec","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0"]}],"windowSettings":{"width":600,"height":1018,"x":5,"y":57,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080},"isMaximized":true,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"reloadAfterResumeTime":120,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"isTwoFactorAutoCatcherEnabled":false,"twoFactorAutoCatcherMatcher":"token, code, sms, verify","showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"enableTranslator":false,"spellcheckerLanguage":"es-US","darkMode":true,"navigationBarManualActive":false,"splitMode":false,"splitColumns":2,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdium without a server","predefinedTodoServer":"https://todoist.com/app","autohideMenuBar":true,"isLockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":false,"hibernationStrategy":3600,"wakeUpStrategy":300,"wakeUpHibernationStrategy":3600,"wakeUpHibernationSplay":true,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":false,"userAgentPref":"","downloadFolderPath":"","adaptableDarkMode":true,"accentColor":"#6840bf","progressbarAccentColor":"#40bf48","serviceRibbonWidth":45,"sidebarServicesLocation":1,"iconSize":30,"sentry":true,"navigationBarBehaviour":"custom","webRTCIPHandlingPolicy":"disable_non_proxied_udp","searchEngine":"duckDuckGo","translatorLanguage":"en","translatorEngine":"LibreTranslate","useHorizontalStyle":false,"hideCollapseButton":true,"isMenuCollapsed":false,"hideRecipesButton":true,"hideSplitModeButton":false,"useGrayscaleServices":false,"grayscaleServicesDim":100,"hideWorkspacesButton":true,"hideNotificationsButton":true,"hideSettingsButton":false,"hideDownloadButton":false,"alwaysShowWorkspaces":false,"hideAllServicesWorkspace":true,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"isTodosFeatureEnabled":true,"customTodoServer":"","locale":"en-US","keepAllWorkspacesLoaded":false,"useSelfSignedCertificates":false,"lockingFeatureEnabled":false},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}```

**Comment by digitalkram** [comment]
same here with KDE on KDE neon - this seems to be a duplicate of: 
 Notifications Stay on Screen #1574

**Comment by SpecialAro** [comment]
Closing as duplicate.
