### ISSUE TITLE
Bluesky service hangs on the logo

### ISSUE THREAD

**Issue by Serene-Arc** [ferdium/ferdium-app#1869]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.6-nightly.8

### Recipe Name

Bluesky

### Recipe Version

1.1.3

### Steps to reproduce

This happens when creating the service for me, without any further changes.

### Expected Behavior

I would expect the app to load to the homepage as it does in the browser.

### Actual Behavior

The Bluesky app loads to the black screen with the butterfly logo and stays there. When looking at the details in the debugging inspecter, there is a tag:

```html
<noscript>
    <h1 lang="en">JavaScript Required</h1>
    <p lang="en">This is a heavily interactive web application, and JavaScript is required. Simple HTML interfaces are possible, but that is not what this is.
    <p lang="en">Learn more about Bluesky at <a href="https://bsky.social">bsky.social</a> and <a href="https://atproto.com">atproto.com</a>.
    
<p>This is the home page.

  </noscript>
```

There are also a number of errors under the console tab.

```
VM436 mobx.cjs.development.js:2474 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@2]' 
TypeError: Cannot read properties of null (reading 'removeAttribute')
    at removeDynamicTheme (VM393 darkreader.js:7486:34)
    at disable (VM393 darkreader.js:7809:9)
    at v.update (VM392 recipe.js:1:8051)
    at VM392 recipe.js:1:3852
    at reactionRunner (VM436 mobx.cjs.development.js:2724:5)
    at trackDerivedFunction (VM436 mobx.cjs.development.js:1850:18)
    at Reaction.track (VM436 mobx.cjs.development.js:2445:18)
    at Reaction.onInvalidate_ (VM436 mobx.cjs.development.js:2705:12)
    at Reaction.runReaction_ (VM436 mobx.cjs.development.js:2411:16)
    at runReactionsHelper (VM436 mobx.cjs.development.js:2562:29)
ExpoLocalization.ts:134 Uncaught 
RangeError: Incorrect locale information provided
    at new Locale (<anonymous>)
    at ExpoLocalization.ts:134:14
    at Array.map (<anonymous>)
    at getLocales (ExpoLocalization.ts:129:21)
    at 95270 (detection.ts:20:3)
    at r (bootstrap:19:32)
    at startup:4:73
    at r.O (chunk loaded:23:12)
    at startup:5:43
    at main.760ec335.js:1:1943966
VM390 renderer_init:2 Electron Security Warning (Node.js Integration with Remote Content) This renderer process has Node.js integration enabled
    and attempted to load remote content from 'https://bsky.app/'. This
    exposes users of this app to severe security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
VM390 renderer_init:2 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
VM436 mobx.cjs.development.js:1819 [MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: RecipeController@1.settings.service
```

**Comment by SpecialAro** [comment]
Hi!

I don't think I'm able to reproduce your issue:
![image](https://github.com/user-attachments/assets/bd48bc6a-d894-44cf-b113-61e99bccfc70)

**Comment by Serene-Arc** [comment]
Hi! I actually have a small update, in that I discovered something strange. I switched to Windows for a game and it turns out that this is a Linux specific issue. I'm running Arch with `ferdium-bin` from the AUR. I'm wondering if it's something strange in the browser/Electron that Ferdium is finding on my system that is Arch specific? I'm not really sure.
