### ISSUE TITLE
Google Mail not loading (Company login)

### ISSUE THREAD

**Issue by Zutatensuppe** [ferdium/ferdium-app#1973]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain (older issues were there, but nothing current)

### Ferdium Version

7.0.0

### What Operating System are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎06/‎08/‎2022 OS build	19045.5131 Experience	Windows Feature Experience Pack 1000.19060.1000.0

### What arch are you using?

x64

### Last Known Working Ferdium version

7.0.0 (it just stopped working suddenly, without updating to a newer Ferdium version, so thats why this is same as above)

### Expected Behavior

Service loads and i can read my emails

### Actual Behavior

After logging in to my account, there is a short loading animation (something rotating, and google being written). But afterwards, everything is grey. There are no errors in the dev console during this process.

before logging in (aka after doing ctrl R to refresh the service):

![image](https://github.com/user-attachments/assets/953a0d6d-7eba-4961-a57c-0a0864ea3665)

after logging in:

![image](https://github.com/user-attachments/assets/a119922a-d01f-425c-b79c-69a13596e738)

after finish rotating:

![image](https://github.com/user-attachments/assets/d10b35ac-33a8-47a2-931f-077c23107eb1)

I have already tried setting user agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36` but it doesn't work.

Gmail still works fine for my personal gmail account, but not for the one at work.

### Steps to reproduce

I don't know if this can be reproduced easily with just any login, as for myself it still works fine with my personal account.

But the steps are:

1. add Gmail service
2. login with company account
3. nothing is displayed after logging in

Additional note: after doing ctrl R to reload the service, i have to relogin.

**Comment by juha-aiven** [comment]
Gmail stopped working for me too today. I've done the usual, "Reload", "Clear Cache", "Disable service" + "Enable Service".

Additionally Google Calendar stopped working exactly the same way.

**Comment by TMaximeP** [comment]
Same here.
I get this error about missing sandbox.json file:

> Uncaught (in promise) Error: C:\Users\...\AppData\Roaming\Ferdium\config\sandboxes.json: ENOENT: no such file or directory, open 'C:\Users\...\AppData\Roaming\Ferdium\config\sandboxes.json'
    at Object.openSync (node:fs:573:18)
    at Object.func [as openSync] (node:electron/js2c/node_init:2:2559)
    at Object.readFileSync (node:fs:452:35)
    at t.readFileSync (node:electron/js2c/node_init:2:10175)
    at readFileSync (C:\Users\...\App…file\index.js:50:22)
    at a._readSandboxes (C:\Users\...\App…\AppStore.js:1:8096)
    at a._initializeSandboxes (C:\Users\...\App…\AppStore.js:1:7710)
    at a.setup (C:\Users\...\App…\AppStore.js:1:7659)
    at a.initialize (C:\Users\...\App…ypedStore.js:1:1394)
    at default (C:\Users\...\App…res\index.js:1:1820)

**Comment by bepipelino** [comment]
We can confirm, that it is also in older versions of ferdium tried _Ferdium-win-AutoSetup-6.7.6-x64.exe_ and cleared also `C:\Users\%user%\AppData\Roaming\Ferdium`. But no effect,  so seems a google issue...
It is also happening on our Macs

**Comment by hyuuki** [comment]
I can confirm that this also happens when I tried to login with my university email (Google Workspace).
Google Calendar, GMail only show blank page, but still works fine with personal account.

**Comment by wgordon17** [comment]
Similarly _also_ impacted by this issue. I'm seeing the redirect flow from corporate SSO and then it just stops at https://accounts.google.com/a/company.com/acs. I'm seeing a few _possibly_ related errors in the console logs

```
/Applications/Ferdiu…obalErrorStore.js:1 Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at WithSortableContainer (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-sortable-hoc/dist/react-sortable-hoc.js:614:7)
    at div
    at TabBar (/Applications/Ferdium.app/Contents/Resources/app.asar/components/services/tabs/Tabbar.js:1:1123)
    at div
    at Sidebar (/Applications/Ferdium.app/Contents/Resources/app.asar/components/layout/Sidebar.js:1:2222)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at injectIntl(inject-with-stores-actions(Sidebar))
    at div
    at div
    at ErrorBoundary (/Applications/Ferdium.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1286)
    at injectIntl(ErrorBoundary)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at AppLayout (/Applications/Ferdium.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2936)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at injectIntl(WithStyles(AppLayout))
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)
    at DefaultPropsProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/DefaultPropsProvider/DefaultPropsProvider.js:18:3)
    at RtlProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/RtlProvider/index.js:19:7)
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:39:5)
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:52:5)
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/styles/ThemeProvider.js:21:14)
    at AppLayoutContainer (/Applications/Ferdium.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1532)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at RenderedRoute (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:539:7)
    at Routes (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1229:7)
    at Router (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1163:17)
    at HistoryRouter (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:770:7)
    at FerdiumRoutes (/Applications/Ferdium.app/Contents/Resources/app.asar/routes.js:1:2693)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at IntlProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:33:47)
    at I18N (/Applications/Ferdium.app/Contents/Resources/app.asar/I18n.js:1:1030)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at Provider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)
/Applications/Ferdiu…obalErrorStore.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `EditSettingsForm`.
    at injectIntl(WithStyles(Input))
    at div
    at div
    at form
    at div
    at div
    at EditSettingsForm (/Applications/Ferdium.app/Contents/Resources/app.asar/components/settings/settings/EditSettingsForm.js:1:10294)
    at injectIntl(EditSettingsForm)
    at ErrorBoundary (/Applications/Ferdium.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1286)
    at injectIntl(ErrorBoundary)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at EditSettingsScreen (/Applications/Ferdium.app/Contents/Resources/app.asar/containers/settings/EditSettingsScreen.js:1:10559)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at injectIntl(inject-with-stores-actions(EditSettingsScreen))
    at RenderedRoute (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:539:7)
    at Outlet (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1142:28)
    at div
    at ErrorBoundary (/Applications/Ferdium.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1286)
    at injectIntl(ErrorBoundary)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at div
    at Transition (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-transition-group/cjs/Transition.js:135:30)
    at CSSTransition (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-transition-group/cjs/CSSTransition.js:120:35)
    at TransitionGroup (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-transition-group/cjs/TransitionGroup.js:57:30)
    at Appear (/Applications/Ferdium.app/Contents/Resources/app.asar/components/ui/effects/Appear.js:1:816)
    at SettingsLayout (/Applications/Ferdium.app/Contents/Resources/app.asar/components/settings/SettingsLayout.js:1:1467)
    at injectIntl(SettingsLayout)
    at ErrorBoundary (/Applications/Ferdium.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1286)
    at injectIntl(ErrorBoundary)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at SettingsContainer (/Applications/Ferdium.app/Contents/Resources/app.asar/containers/settings/SettingsWindow.js:1:1437)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at RenderedRoute (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:539:7)
    at Outlet (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1142:28)
    at div
    at div
    at div
    at ErrorBoundary (/Applications/Ferdium.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1286)
    at injectIntl(ErrorBoundary)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at AppLayout (/Applications/Ferdium.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2936)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25
    at injectIntl(WithStyles(AppLayout))
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)
    at DefaultPropsProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/DefaultPropsProvider/DefaultPropsProvider.js:18:3)
    at RtlProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/RtlProvider/index.js:19:7)
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:39:5)
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:52:5)
    at ThemeProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/styles/ThemeProvider.js:21:14)
    at AppLayoutContainer (/Applications/Ferdium.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1532)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at RenderedRoute (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:539:7)
    at Routes (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1229:7)
    at Router (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1163:17)
    at HistoryRouter (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:770:7)
    at FerdiumRoutes (/Applications/Ferdium.app/Contents/Resources/app.asar/routes.js:1:2693)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at IntlProvider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:33:47)
    at I18N (/Applications/Ferdium.app/Contents/Resources/app.asar/I18n.js:1:1030)
    at /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34
    at Provider (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)
/Applications/Ferdiu…tores/AppStore.js:1 [MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: AppStore@24.autoLaunchOnStart
2
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at IpcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11410)
    at async Promise.all (index 0)
    at async WebViewElement.<anonymous> (/Applications/Ferdiu…s/Service.js:1:8742)
2
/Applications/Ferdiu…i/button/index.js:1 Ferdium Button prop `loaded` will be deprecated in the future. Please use `busy` instead
```

**Comment by wgordon17** [comment]
I've tried reverting to both 6.7.7 and 6.7.6, however neither have made any improvement for resolving this 😞

**Comment by wardragon** [comment]
Same problem is in hangouts chat, try to access to company login. Debian Linux,  tried 7.0 and 7.0.1 nightly build.

**Comment by mjankula** [comment]
same problem on Fedora 40, ferdium 7.0.0 with company gmail as well as company calendar

**Comment by jaklan** [comment]
Same, corporate GCal and Gmail doesn't work since yesterday, tested on various Ferdium versions

**Comment by bepipelino** [comment]
I have the strange feeling, that it has to do with the way google is promoting the use of passkeys during login. I was presented with such dialogs a lot, also in the corporate accounts. Some of my team mates are presented with those "advertisements" during login to use their passkey instead, but they have never set up this feature. Some others are using it, otherwise I would just disable it for testing in the google admin console.

**Comment by bepipelino** [comment]
I can confirm, that only corporate accounts are affected, that use external identity providers (IdP's). Corporate user accounts (like super admins) with a plain google login are not affected.

**Comment by cr3ation** [comment]
Tested with Ferdium Version: 6.7.7 and Version: 7.0.0. Same results. Using corporate accounts with Okta as external identity provider (IdP).

**Comment by martin-kanis** [comment]
Same here, fedora 40, ferdium 6.7.7, corporate google services (gmail, gcalendar, ...) are not loaded after login.

**Comment by vdhmax** [comment]
Same here for corporate gmail services ...

**Comment by Muzosh** [comment]
Maybe it has something to do with certificates? If you search for "GUEST_VIEW_MANAGER_CALL", which is part of my error message, you get a lot of results regarding server certs.
```
invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
```

In my case, my custom server running https://caddyserver.com/ doesn't load either. The Caddy obtains TLS server certificates at Let's Encrypt. There has been issues about self-signed certs #1850 and #1227, but no issues with Let's Encrypt certs.

Now, there are issues emerging with company services (which probably have some non-standard certificates maybe?).

**Comment by jmfinelli** [comment]
Same problem here. Ferdium version 6.7.7

**Comment by RomLecat** [comment]
I think we're all in the same boat, it's unnecessary at this point to spam "Same here" for all users following this issue with notifications :)

**Comment by wgordon17** [comment]
@vraravam I'm wondering what might be the next steps here? Are there more logs or debug information that we can help provide? Is this something unique to Google/Ferdium/Chromium/Electron? Just wondering what might be possible for tracking this down further

**Comment by spirit1jkm** [comment]
Same issue. MacOS 14.6.1, Arm64, Ferdium version 7.0.0. Started today, unable to log back into University Gmail. It starts log in, but once I finish entering credentials, the page is blank. Tried reinstalling the current build and then the beta build. I removed Gmail service and added it back.

**Comment by mfloresVicomtech** [comment]
I can confirm that it is related to Google corporate accounts, no matter what service are you trying to login in. For example, in my case I also have ChatGPT and Trello with same Google corp account and I'm unnable to login.

**Comment by mbentley** [comment]
I am curious - is everyone who is having issues using Okta or some other identity provider?  Instead of spamming the thread with a reply, a 👍  or 👎  to this message would be a quick way to see.

And by the way, I am not a developer and I almost certainly can not fix the issue but I want to try to narrow down what the problem is if at all possible to make it easier for someone who is able to to fix it.

**Comment by jaklan** [comment]
> I am curious - is everyone who is having issues using Okta or some other identity provider? Instead of spamming the thread with a reply, a 👍 or 👎 to this message would be a quick way to see.
> 
> And by the way, I am not a developer and I almost certainly can not fix the issue but I want to try to narrow down what the problem is if at all possible to make it easier for someone who is able to to fix it.

It's related to ACS (sample URL: `https://accounts.google.com/a/foobar.com/acs`), specific IdP shouldn't matter.

https://support.google.com/a/answer/6330801

**Comment by 3gmgithub** [comment]
Issue occurs with Authentik using SAML also.
For some reason logins through the browser (I tried Librewolf, and Chrome) works just fine... Just not in Ferdium.

**Comment by wardragon** [comment]
We are using out personal identity provider, that use shibbolet. Just worked fine until 2 weeks ago. I want to help to debug, but how to enable debug in ferdium? There is an option unto configuration or a command line or the only way is to use the web debugger application? Thanks

**Comment by julienchamp** [comment]
Same issue here (when I login to gmail/calendar with Okta)

I think it's the same than here : https://github.com/ferdium/ferdium-app/issues/1845

**Comment by raulmatei** [comment]
Hello,

Some more details on this.
My company account is authenticated with Okta, authentication which is successful. 

Okta redirects to https://www.google.com/a/8x8.com/acs and it loads an HTML document which contains a form with some SAML details. The form is auto-submitted using JavaScript. The response is a similar HTML document which contains a similar form that is expected to also be auto-submitted. The problem is that the second request seems to get canceled for some reasons, see below screenshot:
![image](https://github.com/user-attachments/assets/811eac94-6ae2-4ed9-a95d-4c62fd05ca00)

This means the second request never reaches the Google server and the authentication process stops.

What I did to get into the account was to resubmit the second request by typing: `document.forms["hiddenpost"].submit();` in the console. This will resubmit the second form and you get authenticated.

Unfortunately, I'm not able to replicate the same flow twice. It worked once, but can't make it work the second time.  

**Later edit:**
I managed to make it work the second time, but it's a bit complicated and I'll have to repeat it multiple times and note down the steps. Will update in this thread once I get to a consistent flow if anyone wants to try it out.

**Comment by k-y** [comment]
I tried to use @raulmatei's method but it didn't work, here's a screenshot of an error from my console:
![image](https://github.com/user-attachments/assets/7dbf3f63-f89b-4149-a9dc-1e6290e256f5)

**Comment by raulmatei** [comment]
Here are the steps to make it work on a Windows machine (I don't have access to other OSes but it probably works on these too). It's a very technical flow and it requires a lot of patience. The process is harmless and should not affect anything on your machine, OS or Ferdium app, but try it at your on risk.

1. open Ferdium and go to the top menu and click on `View → Toggle Navigation Bar (Ctrl+B)` if the navigation bar it's not visible and then `View → Toggle Service Developer Tools (Ctrl+Shift+Alt+I)`
![image](https://github.com/user-attachments/assets/fd6de09a-4483-48d2-8f59-c0be16821318)
![image](https://github.com/user-attachments/assets/477bb78f-bd1b-426f-ad39-3c713c516016)
2. the devtools will open as a detached window
3. on the devtools select the `Network` tab
![image](https://github.com/user-attachments/assets/6afb5292-7272-4811-acbb-ae1b31f8e81c) 
and enable `Preserve log`  on the first line under the `Network` tab
![image](https://github.com/user-attachments/assets/806db873-547c-4b6e-9fda-525add52f0d2)
4. move to main Ferdium app window
5. type your username into the Google signing form and hit Next - it will redirect you to your 3rd party authentication provider (Okta, MS Asure, or any custom ones) - make sure to follow the steps for the authentication process based on the specific provider's flow
6. once you're redirected to the `https://accounts.google.com/a/8x8.com/acs` page with a gray background 
![image](https://github.com/user-attachments/assets/1c343328-2cab-4eb3-934f-7833a7c831ad)
move to the devtools window and try to identify the canceled request:
![image](https://github.com/user-attachments/assets/9c38fc72-e0f1-44bf-a18d-1f9fd6b85af8)
7. find the `acs` request on top of it and click on that row
![image](https://github.com/user-attachments/assets/aba8c6e0-c361-4543-89d1-d1ae6a7452a6)
8. a separate panel should open on the right presenting more information about the request, go to `Response` tab on that panel, at this point it should say `Failed to load response data: No resource with given identifier found`
![image](https://github.com/user-attachments/assets/25da079a-d329-48ef-bbb5-9d28de3d3905)
if that's the case, move to next step - if it has content move to step `11`
9.  while keeping the `acs` request selected in the devtools window with the `Response` tab opened, go back to the main Ferdium app window and type your service url in the address bar: `https://calendar.google.com` in my case, but it can be any of their services - after this action you should be back to the login form - follow the steps again and pay attention to the detached devtools window - you'll have to select the `acs` request once it's fired to be able to get the response content, otherwise it will continue to show `Failed to load response data: No resource with given identifier found` - this is the most tricky part and it requires a lot of patience to get it working - if the requests are fired too fast you have the option to set a throttling profile by selecting one from the top of the devtools window:
![image](https://github.com/user-attachments/assets/3f25120a-dfce-4e8c-8974-940a9b185e7a)
For me selecting `3G` option slows down the request enough to be able to select the first `acs` request row and get the response content
![image](https://github.com/user-attachments/assets/b4caf3f4-7209-49e6-8b52-8a4d3cce2a1d)
I managed to make it work even without the throttling options selected, but it's too fast sometimes and I miss it. Pay attention that there are some other requests that are fired after this one, please select the first `acs` request and wait for all requests to finish and then reselect the `acs` one before the canceled one - even if the panel will be closed the response content will be there if you selected it before the one that's canceled is fired (it's tricky,  I know)
10. once you have it selected and `Response` tab open, you should see something like this:
![image](https://github.com/user-attachments/assets/62668d8c-9f00-456a-ba1a-c18b07a57fbc)
if you don't see it, repeat step 13 until you get the response content
11. once you have the response content available click anywhere inside the response tab and then `CTRL+A` to select the entire content and then `CTRL+C` to copy it
12. once you have it copied move to the `Elements` tab and right click on the `<html>` tab and select `Edit as HTML` and then remove everything and paste (`CTRL+V`) the content copied on the previous step and click outside the box or hit `CTRL+ENTER` to save it
13. once you have the HTML content pasted and visible in the `Elements` tab open the `Console` panel (hit `ESC` again if you closed it, if not it should still be at the bottom of the detached devtools window) and type `document.forms["hiddenpost"].submit();` (pasting is disabled by default but if you want to just copy/paste it from here, type `allow pasting` in the console and hit `ENTER` and it will allow you to paste content, otherwise it will show a warning)
![image](https://github.com/user-attachments/assets/222a2dd0-29e8-468a-b467-216711003104)
14. once you have the above command pasted into the console, hit `ENTER` and wait - this will submit the form inside the HTML content and will finalize the authentication process redirecting you to the selected service (as a side note, if you enabled throttling, disable it before executing this step, to speed up the rest of the process)

Make sure to execute steps 11 to 14 as fast as possible, the credentials will expire in a few minutes and you'll have to repeat the process again from step 9. If the process is successful, close all devtools instances and just use Ferdium as you did before this issue appeared. You'll have to repeat the process once your session expires. You also need to repeat the process for all Google services that are using 3rd party authentication providers. I don't know if there are issues with other non-Google services while using a 3rd party authentication provider and I haven't tested this with anything else than Google services (Gmail and Calendar). Please report back if it works for other cases as it might help other users.

**Comment by mbentley** [comment]
@raulmatei - thanks for taking the time to outline the steps!  This worked for me to allow me to sign in - very tedious but worth it to get it working again.  Certainly helps using the newer sandbox feature so that I only had to do the steps once instead of three times for my work services.  I hope that the steps might help someone also understand how to resolve the issue as well.

The only thing I also had to do was toggle on the navigation bar from the view menu as I did not have that enabled.

**Comment by mbentley** [comment]
Just as an update, I can simplify steps 1-6 by directly opening `View` > `Toggle Service Developer Tools` which is the next item in your screen shot but is truncated.  That opens the dev tools for the specific service without having to identify it in the HTML of Ferdium.

**Comment by raulmatei** [comment]
> Just as an update, I can simplify steps 1-6 by directly opening `View` > `Toggle Service Developer Tools` which is the next item in your screen shot but is truncated. That opens the dev tools for the specific service without having to identify it in the HTML of Ferdium.

Great, I'll update the steps later today

**Comment by 3gmgithub** [comment]
Thank you for these steps! That worked, but took a few minutes to get the response data.  Hopefully we can find a way to update Ferdium so it will work with these accounts.

**Comment by bepipelino** [comment]
So for one service (google caledar), it worked like a charm, but with gmail and other services, connected to google social login I always get stuck here (with a never ending progress spinner) : 
any Ideas?
![ferdium_issue_google_login](https://github.com/user-attachments/assets/f8e85fdd-c4ff-4ec1-9def-50225849edaa)
![2024-12-05 16_09_19-](https://github.com/user-attachments/assets/347a77a4-50e0-49cf-80a0-7eb35c382a92)

**Comment by wgordon17** [comment]
Certainly annoying! But at least I got it working! Thanks @raulmatei!! 🎉 Now, this should _hopefully_ give me 2 weeks before my session expires and I have to do this all over again 🙄

**Comment by raulmatei** [comment]
> So for one service (google caledar), it worked like a charm, but with gmail and other services, connected to google social login I always get stuck here (with a never ending progress spinner) : any Ideas?

Not sure, but have you invoked: `document.forms["hiddenpost"].submit();` - that spiner shows when you copy/paste the HTML content and it's still spinning because this GIF: 
![image](https://github.com/user-attachments/assets/b42008d0-b812-46a5-a71f-ae76036b5282)
is rendered in the page and once it's loaded it will spin forever.

Make sure to invoke the submit method and also, if you enabled throttling, disable it - otherwise it will take a few seconds per request and the whole flow will take a while.

**Comment by featherbear** [comment]
My workaround (working for Gmail and Calendar) seems to work on the first go.

1) Open [View] -> [Toggle Service Developer Tools]
2) Go to the [Network] tab
3) Enable [Preserve log]
4) Perform your authentication flow and wait for the the blank end-page
5) Find the cancelled `acs` endpoint request
6) Right-click the entry, and copy the request (see image below)
<img width="711" alt="image" src="https://github.com/user-attachments/assets/42e5d5c5-2b84-4fc9-b62a-c7dee8e22356">

7) Go to the [Console] tab
8) Paste the request (you may need to type `allow pasting` and hit Enter first)
9) Go back to the [Network] tab, you should now see that there is a new entry for a request to `acs`
10) In the [Response] view, locate the `<script>` tag pair and copy its code contents
<img width="855" alt="image" src="https://github.com/user-attachments/assets/2f3cf93b-b843-4b32-adf8-5b6d908e04fe">

11) Go back to the [Console] tab, paste and press enter
12) ???
13) Profit

**Comment by vvvlc** [comment]
Hi
Any plan/ETA to fix this?
Regards
Vitek

**Comment by wardragon** [comment]
So the workaround proposed by [featherbear](https://github.com/ferdium/ferdium-app/issues/1973#issuecomment-2521914181) is working also on linux. So, how we can achive this and make do this into ferdium? Anyone as an idea how we can help to modify the code and make this work?

**Comment by miguelsvieira** [comment]
[Featherbear's workaround](https://github.com/ferdium/ferdium-app/issues/1973#issuecomment-2521914181) works for me as well, including for Google Chat and Calendar -- but those steps have to be repeated every time I'm automatically logged out from the services (every couple of days, in my case).

**Comment by larsonius** [comment]
This workaround is extremely fiddly and not sustainable. I can't use Ferdium like this.

Does anyone here care that the software is losing users? Nothing has happened here for months. Dear developers of this wonderful software, please give us an update!

Thanks in advance,
Lars

**Comment by jmfinelli** [comment]
I agree. Unfortunately, Ferdium cannot be used with this bug. Personally, I migrated to:
- Vivaldi -> but I quickly ditched it because its performance degrades in proportion to the number of open tabs
- Arc Browser -> great choice, and I’m currently using it as my default browser. There are some cons (e.g., poor bookmark management, limited cookie customisation, and the fact that it's not open source), but overall, it’s a good browser
- Zen Browser – I just found out about this one. It’s similar to Arc but open source

**Comment by wgordon17** [comment]
I switched over to [Sidekick](https://www.meetsidekick.com/), it's been a good experience so far

**Comment by k-y** [comment]
Surely there's a way to userscript the process at least?

**Comment by 3gmgithub** [comment]
> I agree. Unfortunately, Ferdium cannot be used with this bug. Personally, I migrated to:
> 
> * Vivaldi -> but I quickly ditched it because its performance degrades in proportion to the number of open tabs
> * Arc Browser -> great choice, and I’m currently using it as my default browser. There are some cons (e.g., poor bookmark management, limited cookie customisation, and the fact that it's not open source), but overall, it’s a good browser
> * Zen Browser – I just found out about this one. It’s similar to Arc but open source

Zen Browser is good, but has some really nasty bugs still... Try using it will dual-screens and multiple windows.
Or with Tab Groups...

There is a reason it is still in beta...

**Comment by AdamModus** [comment]
Also feeling this, which makes me not able to use Ferdium :/
I am currently using Rambox, without any issues, but I do prefer the minimalist approach and UI of Ferdium.

**Comment by adam-vest** [comment]
Not even the workaround described here is working reliably anymore. Google will usually just complain that the SAML auth was reused and demand I start fresh. And since there's no way to clear auth sessions, this involves deleting the service, adding the service back, and trying the workaround again in hopes that it just so happens to work that time.

**Comment by abhi-uoh** [comment]
currently facing an issue where I’m unable to log in to Gmail, Gemini, or use Google SSO to log into any services. This issue persists across all attempts.

Device Details:
	•	Device: MacBook Pro 16-inch (Nov 2023)
	•	Chip: Apple M3 Pro
	•	Memory: 36 GB
	•	OS: macOS Sequoia 15.5

**Comment by lef** [comment]
I think we should proceed with the following steps:

1. First, consolidate the related issues for better tracking. Relevant issues include #1128 and #2082.
2. Then, decide whether addressing only the Google ACS issue is sufficient — I’m not certain about this yet.
3. Finally, someone will need to create a PR to move this forward.

This discussion has been ongoing since 2023 with little progress, so I believe we should raise its priority.

**Comment by mbentley** [comment]
Look, I have no idea if this will break other stuff and in full transparency, I used Claude Code to figure out why this was happening and I have a change that seems to fix it: https://github.com/mbentley/ferdium-app/commit/e556c68f0206c848bbc9abee7b1d881760efe573

It looks like this code was originally added in https://github.com/ferdium/ferdium-app/commit/2ad39ffb1cb0d0e5f79d6948f798ca79ed73c76c

I had Claude do some analysis of why this shouldn't break things
What that commit did:
Added chromeless user agent for Google login (removes Chrome version)
Added the forwardingHack parameter with loadURL() to reload the page
This was needed because TickTick requires Chrome version, but Google blocks it
The problem with the original approach:
The loadURL() reload was a workaround to apply the user agent change
It worked for simple GET requests
But it breaks POST requests (like SAML SSO) by canceling and reloading them as GET
Why Our Fix is Safe
What changed in Electron since 2021: The commit is from June 2021. Modern Electron (which Ferdium now uses) applies user agent changes immediately to ongoing navigation without needing a reload. Our fix:
✅ Still sets this.webview.userAgent = this.userAgent (line 90)
✅ Chromeless user agent still applies to Google accounts
✅ TickTick still gets the chromeless user agent it needs
❌ No more loadURL() that cancels POST requests
✅ SSO/SAML now works (as you confirmed!)


I did test to see if TickTick authentication still works and it does.

I am going to submit a PR to get someone to look at it because I am tired of using the workaround.

**Comment by bear454** [comment]
When can we expect a release with the fix included?

**Comment by Alphrag** [comment]
> When can we expect a release with the fix included?

Tomorrow for the nightly builds, and I will wait a few days for a stable one so hopefully this weekend if I find the time to deal with it.

**Comment by josecastillolema** [comment]
This is amazing! Thanks everyone that worked on this fix.
Could we please get a new flathub release with the fix?
If anyone can confirm if the fix made it to latest releases I can open a PR to update the flathub version.
