### ISSUE TITLE
[Bug]: Cannot add new service for Jitsi and Jira

### ISSUE THREAD

**Issue by cedricroijakkers** [ferdium/ferdium-app#401]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.81 (Windows) & 6.0.0-nightly.82 (Linux), possibly earlier versions too

### Recipe Name

Jitsi and Jira

### Recipe Version

Not sure

### Last Known working version of the recipe

Not sure

### Steps to reproduce

1. Click on Services -> Add New Service
2. Select Jitsi Meet
3. Get a blank screen with "Something went wrong" and a Reload button (see screenshot)
![image](https://user-images.githubusercontent.com/15158042/176621663-e3a55a23-f6a0-4b5a-a609-b648ba4bb98d.png)

Also reproducible with Jira, but i.e. not with Confluence or Gmail.

### Expected Behavior

Adding the service should work

### Actual Behavior

Get an empty screen when adding the service

### Additional Information

Developer tools give this error when adding Jitsi:

```
/opt/ferdium/resourc….development.js:325 Uncaught TypeError: Cannot read properties of null (reading 'team')
    at EditServiceForm.render (/opt/ferdium/resourc…rviceForm.js:1:6512)
    at Object.allowStateChanges [as _allowStateChanges] (/opt/ferdium/resourc…/lib/mobx.js:991:15)
    at /opt/ferdium/resourc…velopment.js:318:26
    at trackDerivedFunction (/opt/ferdium/resourc…/lib/mobx.js:776:24)
    at Reaction.track (/opt/ferdium/resourc…lib/mobx.js:1806:22)
    at EditServiceForm.reactiveRender [as render] (/opt/ferdium/resourc…velopment.js:316:14)
    at EditServiceForm.makeComponentReactive (/opt/ferdium/resourc…velopment.js:331:25)
    at target.render (/opt/ferdium/resourc…velopment.js:244:34)
    at finishClassComponent (/opt/ferdium/resourc…lopment.js:17485:31)
    at updateClassComponent (/opt/ferdium/resourc…lopment.js:17435:24)
/opt/ferdium/resourc…obalErrorStore.js:1 The above error occurred in the <EditServiceForm> component:

    at EditServiceForm (/opt/ferdium/resources/app.asar/components/settings/services/EditServiceForm.js:1:5345)
    at injectIntl(EditServiceForm)
    at ErrorBoundary (/opt/ferdium/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)
    at injectIntl(ErrorBoundary)
    at /opt/ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at EditServiceScreen (/opt/ferdium/resources/app.asar/containers/settings/EditServiceScreen.js:1:3234)
    at /opt/ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at injectIntl(inject-with-stores-actions(EditServiceScreen))
    at div
    at ErrorBoundary (/opt/ferdium/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)
    at injectIntl(ErrorBoundary)
    at /opt/ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at div
    at CSSTransitionGroupChild (/opt/ferdium/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroupChild.js:83:5)
    at span
    at TransitionGroup (/opt/ferdium/resources/app.asar/node_modules/react-transition-group/TransitionGroup.js:50:5)
    at CSSTransitionGroup (/opt/ferdium/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroup.js:56:5)
    at Appear (/opt/ferdium/resources/app.asar/components/ui/effects/Appear.js:1:447)
    at SettingsLayout (/opt/ferdium/resources/app.asar/components/settings/SettingsLayout.js:1:883)
    at injectIntl(SettingsLayout)
    at ErrorBoundary (/opt/ferdium/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)
    at injectIntl(ErrorBoundary)
    at /opt/ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at SettingsContainer (/opt/ferdium/resources/app.asar/containers/settings/SettingsWindow.js:1:826)
    at /opt/ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at div
    at div
    at div
    at ErrorBoundary (/opt/ferdium/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)
    at injectIntl(ErrorBoundary)
    at /opt/ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at AppLayout (/opt/ferdium/resources/app.asar/components/layout/AppLayout.js:1:2631)
    at /opt/ferdium/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(AppLayout))
    at ThemeProvider (/opt/ferdium/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)
    at AppLayoutContainer (/opt/ferdium/resources/app.asar/containers/layout/AppLayoutContainer.js:1:876)
    at /opt/ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at <anonymous> (/opt/ferdium/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at <anonymous> (/opt/ferdium/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at Routes (/opt/ferdium/resources/app.asar/routes.js:1:2444)
    at /opt/ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at IntlProvider (/opt/ferdium/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)
    at I18N (/opt/ferdium/resources/app.asar/I18n.js:1:470)
    at /opt/ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at Provider (/opt/ferdium/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by cino** [comment]
@cedricroijakkers Thanks for opening this issue, I've just moved it to the ferdium-app repo as we discovered it's not specific to the jira/jitsi applications but this is a bug regarding all services that include a `selfHosted` setting. A PR has been opened just now and will be included in the upcoming nightly release after merging.
