### ISSUE TITLE
Bug: In KDE menus are not rendering / broken

### ISSUE THREAD

**Issue by guedressel** [ferdium/ferdium-app#560]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.1-nightly.14

### What Operating System are you using?

Other (specify below)

### Operating System Version

KDE/Plasma (experienced on Arch and Kubuntu 22.04 - all I use)

### What arch are you using?

x64

### Last Known Working Ferdium version

Never worked - did work in Ferdi though

### Expected Behavior

Menus may pop-up as usual in other applications

### Actual Behavior

Menus are not rendered correctly and block the KDE/Plasma UI for some time.

### Steps to reproduce

Click on either a menu bar item or try to open the context menu (mouse right click)

### Screenshots

![Ferdium KDE Render Issues 2022-08-18 11-05](https://user-images.githubusercontent.com/1841616/185356663-ea0b8d75-9c78-4824-be5e-d6cc333ef72e.gif)

### Additional information

"About Ferdium" output:

```
Version: 6.0.1-nightly.14
Server: No Server
Electron: 20.0.2
Chrome: 104.0.5112.81
Node.js: 16.15.0
Platform: Linux 5.15
Arch: x64
Build date: Fri Aug 12 2022 04:34:27 GMT+0200 (Central European Summer Time)
Git SHA: 53b5b5c6
Git branch: nightly
```

"Copy Debug Information" output:

```json
{"host":{"platform":"linux","release":"5.15.0-41-generic","screens":[{"id":3850489720471634,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":60,"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":true,"touchSupport":"unknown"},{"id":8565007717795157,"bounds":{"x":1920,"y":0,"width":2560,"height":1080},"workArea":{"x":1920,"y":0,"width":2560,"height":1044},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1080},"displayFrequency":59,"workAreaSize":{"width":2560,"height":1044},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdium":{"version":"6.0.1-nightly.14","electron":"20.0.2","installedRecipes":[{"id":"discord","version":"1.7.8"},{"id":"element","version":"1.3.0"},{"id":"hangoutschat","version":"1.6.0"},{"id":"rocketchat","version":"1.3.0"},{"id":"slack","version":"1.4.2"},{}],"devRecipes":[],"services":[{"id":"b93b8f41-5ef8-428a-9751-10cbeba0c78c","recipe":"hangoutschat","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"86048522-d2e7-46c6-9692-f9605cb8537d","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"4e6057e8-a16d-4245-8fbe-fa6971372ef5","recipe":"rocketchat","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"2b4d1e09-b920-4b7b-87b9-d75959fb2f5d","recipe":"element","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"33a12cda-3a02-489b-a294-5a3a409819e3","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `PublishDebugLogModal`, expected instance of `ServicesStore`.","\n    at PublishDebugLogModal (/snap/ferdium/104/resources/app.asar/features/publishDebugInfo/Component.js:1:2582)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(PublishDebugLogModal)))\n    at AuthLayout (/snap/ferdium/104/resources/app.asar/components/auth/AuthLayout.js:1:1224)\n    at injectIntl(AuthLayout)\n    at ThemeProvider (/snap/ferdium/104/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AuthLayoutContainer (/snap/ferdium/104/resources/app.asar/containers/auth/AuthLayoutContainer.js:1:598)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Routes (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:887:7)\n    at Router (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:821:17)\n    at HistoryRouter (/snap/ferdium/104/resources/app.asar/node_modules/react-router-dom/umd/react-router-dom.development.js:144:7)\n    at FerdiumRoutes (/snap/ferdium/104/resources/app.asar/routes.js:1:2789)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/snap/ferdium/104/resources/app.asar/node_modules/react-intl/src/components/provider.js:84:47)\n    at I18N (/snap/ferdium/104/resources/app.asar/I18n.js:1:506)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"default"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `Sidebar`, expected instance of `SettingsStore`.","\n    at Sidebar (/snap/ferdium/104/resources/app.asar/components/layout/Sidebar.js:1:2062)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at injectIntl(inject-with-stores-actions(Sidebar))\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/104/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)\n    at injectIntl(ErrorBoundary)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at AppLayout (/snap/ferdium/104/resources/app.asar/components/layout/AppLayout.js:1:2751)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/104/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/104/resources/app.asar/containers/layout/AppLayoutContainer.js:1:923)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Routes (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:887:7)\n    at Router (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:821:17)\n    at HistoryRouter (/snap/ferdium/104/resources/app.asar/node_modules/react-router-dom/umd/react-router-dom.development.js:144:7)\n    at FerdiumRoutes (/snap/ferdium/104/resources/app.asar/routes.js:1:2789)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/snap/ferdium/104/resources/app.asar/node_modules/react-intl/src/components/provider.js:84:47)\n    at I18N (/snap/ferdium/104/resources/app.asar/I18n.js:1:506)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `QuickSwitchModal`, expected instance of `ServicesStore`.","\n    at QuickSwitchModal (/snap/ferdium/104/resources/app.asar/features/quickSwitch/Component.js:1:2000)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(QuickSwitchModal)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/104/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)\n    at injectIntl(ErrorBoundary)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at AppLayout (/snap/ferdium/104/resources/app.asar/components/layout/AppLayout.js:1:2751)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/104/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/104/resources/app.asar/containers/layout/AppLayoutContainer.js:1:923)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Routes (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:887:7)\n    at Router (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:821:17)\n    at HistoryRouter (/snap/ferdium/104/resources/app.asar/node_modules/react-router-dom/umd/react-router-dom.development.js:144:7)\n    at FerdiumRoutes (/snap/ferdium/104/resources/app.asar/routes.js:1:2789)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/snap/ferdium/104/resources/app.asar/node_modules/react-intl/src/components/provider.js:84:47)\n    at I18N (/snap/ferdium/104/resources/app.asar/I18n.js:1:506)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `SettingsNavigation`, expected instance of `SettingsStore`.","\n    at SettingsNavigation (/snap/ferdium/104/resources/app.asar/components/settings/navigation/SettingsNavigation.js:1:1773)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at injectIntl(inject-with-stores-actions(SettingsNavigation))\n    at div\n    at ErrorBoundary (/snap/ferdium/104/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)\n    at injectIntl(ErrorBoundary)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at div\n    at CSSTransitionGroupChild (/snap/ferdium/104/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroupChild.js:83:5)\n    at span\n    at TransitionGroup (/snap/ferdium/104/resources/app.asar/node_modules/react-transition-group/TransitionGroup.js:50:5)\n    at CSSTransitionGroup (/snap/ferdium/104/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroup.js:56:5)\n    at Appear (/snap/ferdium/104/resources/app.asar/components/ui/effects/Appear.js:1:375)\n    at SettingsLayout (/snap/ferdium/104/resources/app.asar/components/settings/SettingsLayout.js:1:945)\n    at injectIntl(SettingsLayout)\n    at ErrorBoundary (/snap/ferdium/104/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)\n    at injectIntl(ErrorBoundary)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at SettingsContainer (/snap/ferdium/104/resources/app.asar/containers/settings/SettingsWindow.js:1:873)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Outlet (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:798:28)\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/104/resources/app.asar/components/util/ErrorBoundary/index.js:1:822)\n    at injectIntl(ErrorBoundary)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at AppLayout (/snap/ferdium/104/resources/app.asar/components/layout/AppLayout.js:1:2751)\n    at /snap/ferdium/104/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/104/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/104/resources/app.asar/containers/layout/AppLayoutContainer.js:1:923)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Routes (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:887:7)\n    at Router (/snap/ferdium/104/resources/app.asar/node_modules/react-router/umd/react-router.development.js:821:17)\n    at HistoryRouter (/snap/ferdium/104/resources/app.asar/node_modules/react-router-dom/umd/react-router-dom.development.js:144:7)\n    at FerdiumRoutes (/snap/ferdium/104/resources/app.asar/routes.js:1:2789)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/snap/ferdium/104/resources/app.asar/node_modules/react-intl/src/components/provider.js:84:47)\n    at I18N (/snap/ferdium/104/resources/app.asar/I18n.js:1:506)\n    at /snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/snap/ferdium/104/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"}],"workspaces":[{"id":"cf8b145d-e3f6-411b-9554-627cfe011cf5","services":["2b4d1e09-b920-4b7b-87b9-d75959fb2f5d","33a12cda-3a02-489b-a294-5a3a409819e3"]}],"windowSettings":{"width":1636,"height":955,"x":54,"y":29,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"reloadAfterResumeTime":10,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":true,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"navigationBarManualActive":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdium without a server","predefinedTodoServer":"https://app.nozbe.com/#login","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"wakeUpHibernationStrategy":0,"wakeUpHibernationSplay":true,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","progressbarAccentColor":"#7367F0","serviceRibbonWidth":68,"sidebarServicesLocation":0,"iconSize":20,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useHorizontalStyle":false,"hideCollapseButton":false,"isMenuCollapsed":false,"hideRecipesButton":false,"hideSplitModeButton":true,"useGrayscaleServices":false,"grayscaleServicesDim":50,"hideWorkspacesButton":false,"hideNotificationsButton":false,"hideSettingsButton":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"customTodoServer":"","locale":"en-US","useVerticalStyle":false},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by mtszsobczak** [comment]
I have the same issue on i3 WM installed on top of ubunte mate on both 22.04 and 20.04. This also pretty often freezes Ferdi/Ferdium and whole WM.

I had this problem with Ferdi.

**Comment by mcmxcdev** [comment]
I cannot reproduce this on Ubuntu 23.04 with 6.4.1 stable, both the menu as well as context menu inside different services work as expected!

Do you guys still experience this issue?

**Comment by mtszsobczak** [comment]
Yes, it is still happening with Ferdium 6.4.1 and mate ubuntu 22.04.3 with i3.

![image](https://github.com/ferdium/ferdium-app/assets/9355059/25afa6f0-a42e-4cae-9a5d-84261056dcdb)
