### ISSUE TITLE
Bug: Ferdium won't open in Windows

### ISSUE THREAD

**Issue by Ansem93** [ferdium/ferdium-app#932]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 22h2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.x

### Expected Behavior

When I try to open Ferdium it should open

### Actual Behavior

When I try to open Ferdium I see 3 tasks in the task manager but the UI won't open. 
I tried to uninstall and install the latest version but nothing changed
It's basically impossible to use it

From the screenshot: 3 running tasks from Ferdium, but the app is not open neither in the task bar and tray bar.

### Steps to reproduce

1. Open Ferdium
2. Look at tasks in the task manager

### Screenshots

![2023_01_20 - 15_05_13 - Discord](https://user-images.githubusercontent.com/6626218/216848066-0b7dce99-231a-4df9-ba63-e8bfd77c202c.jpg)

**Comment by marnovo** [comment]
Similar behavior on 6.2.4 but in macOS: app opens, briefly seems loaded normally but then no windows show up. See behavior reflection in menu bar:
https://user-images.githubusercontent.com/15906764/216970149-35d42aa8-ff67-4b8a-83b6-cae168136726.mov
Maybe also related to https://github.com/ferdium/ferdium-app/issues/923

**Comment by Willizxy** [comment]
Exact same behaviour for me also on Windows 11 as of this morning

**Comment by robbionline** [comment]
I have a similar problem on Manjaro. It started some days ago. Ferdium (6.2.4 snap) doesn't start at all. If I try to start it via terminal, I get the following output:

> $ ferdium
> 
> update.go:85: cannot change mount namespace according to change mount (/run/user/1000/doc/by-app/snap.ferdium /run/user/1000/doc none bind,rw,x-snapd.ignore-missing 0 0): cannot inspect "/run/user/1000/doc": lstat /run/user/1000/doc: permission denied
> 
> Gtk-Message: 11:17:36.075: Failed to load module "xapp-gtk3-module"
> 
> Gtk-Message: 11:17:36.076: Failed to load module "xapp-gtk3-module"
> 
> Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by Ansem93** [comment]
Deleting the folder  %AppData%/Ferdium will make ferdium work again, but of course you'll lose everything.

After playing around, I can confirm that the issue is with something inside the config folder.
I renamed ferdium_old the folder, then moved one subfolder at time and it stopped opening as soon as I moved the config folder

**Comment by kevintaw2** [comment]
It works for me like this:

Open %AppData%

1. I renamed the folder from Ferdium to ferdium_old
2. Open the Ferdium App
3. It will create a new Ferdium folder
4. Quit ferium
5. Copy the "config" folder
6. Paste to your old folder
7. Delete "Ferdium" folder
8. Done

**Comment by JackGraymer** [comment]
A bit more refined, the problem comes with the settings.json in the config folder.
For me it worked with:

1. Close Ferdium on the task manager
2. Delete **settings.json** from **AppData\Roaming\Ferdium\config**
3. Reopen Ferdium

It will create a new settings.json. 
In my case it deleted the master PIN code. Big security flaw?

**Comment by vraravam** [comment]
Sorry - this was troubleshooted in our Discord channel by me sometime ago. I thought it was the same OP from here who had posted there. Yes, a corrupted `config/settings.json` can cause issues. The simplest solution is to take a backup of that file when you know Ferdium is working. If the above behavior is faced, then replace with the backup after quitting Ferdium.

**Comment by JackGraymer** [comment]
That is great news.

Maybe someone should leave this answer in github issues and close the it.

**Comment by francwalter** [comment]
I had this "Something went wrong" crash too, I renamed the settings.json (it is in: c:\Users\f\AppData\Roaming\Ferdium\config\settings.json) to ...bak and restarted Ferdium to recreate it, then I compared it.
I found different:

    "hibernationStrategy": "300",
    "wakeUpStrategy": "300",
    "wakeUpHibernationStrategy": "0",

this was:

    "hibernationStrategy": 300,
    "wakeUpStrategy": 300,
    "wakeUpHibernationStrategy": 0,

so the values were without quotes. I dont know if that is important now, I am on 6.3.0-nightly.14 on Windows 10.
Since I changed that (took the new created settings.json and changed only my personal settings, but kept the quotes from the new settings.json file, no more crash. But this is just some minutes (it crashed faster than a minute before, though).
frank

**Comment by kastnerp** [comment]
Same behavior in `6.6.0`. Tried all the suggestions in this thread, nothing worked. 
Opening in terminal reported:

```
SyntaxError: C:\Users\USER\AppData\Roaming\Ferdium\config\proxy.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileSync (C:\Users\USER\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\jsonfile\index.js:52:17)
    at n._hydrate (C:\Users\USER\AppData\Local\Programs\Ferdium\resources\app.asar\electron\Settings.js:1:1313)
    at new Settings (C:\Users\USER\AppData\Local\Programs\Ferdium\resources\app.asar\electron\Settings.js:1:1007)
    at Object.<anonymous> (C:\Users\USER\AppData\Local\Programs\Ferdium\resources\app.asar\index.js:1:2226)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
```

After deleting `proxy.json` the app opens again, however, all my services are gone…

**Comment by pktiuk** [comment]
Same problem on Linux with Flatpak

```
$ flatpak run org.ferdium.Ferdium
SyntaxError: /home/pawel/.var/app/org.ferdium.Ferdium/config/Ferdium/config/settings.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileSync (/app/Ferdium/resources/app.asar/node_modules/jsonfile/index.js:52:17)
    at n._hydrate (/app/Ferdium/resources/app.asar/electron/Settings.js:1:1313)
    at new Settings (/app/Ferdium/resources/app.asar/electron/Settings.js:1:1007)
    at Object.<anonymous> (/app/Ferdium/resources/app.asar/index.js:1:2173)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
Gtk-Message: 17:20:21.358: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:20:21.360: Failed to load module "canberra-gtk-module"

```

**Comment by pktiuk** [comment]
After removing problematic files my services are gone, but still the app is broken. I get `Could not load services and user information`

Terminal shows:

```
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@13.store
[2:1207/172831.471962:ERROR:nss_util.cc(239)] Error initializing NSS with a persistent database (sql:/home/pawel/.pki/nssdb): NSS error code: -8126
```

**Comment by alescinskis** [comment]
not able to open ferdium 6.7.0 on windows 10, it just appears in task managed and that's it.

**Comment by bsdev90** [comment]
It happened to me today, Windows 11. I opened the config.json file with Notepad++ and it was totally corrupted.
Deleted it and proxy.json (same problem), it works. Services was still here but all Ferdium configuration had to be done.
Now, I backuped the two json files.

**Comment by andbad** [comment]
Same here. Windows 11. 

By(t)e

**Comment by JackGraymer** [comment]
Delete **config.json ** and **proxy.json if needed**. 
Reopen ferdium, check and apply desired configuration. 
Create a backup of the file and save it in a subfolder.
Use backup when issue arises.

**Comment by andbad** [comment]
Yes, I had read. An unpleasant problem but easy to resolve (if you find this issue).

Byte

**Comment by everforyou** [comment]
> It works for me like this:
> 
> Open %AppData%
> 
> 1. I renamed the folder from Ferdium to ferdium_old
> 2. Open the Ferdium App
> 3. It will create a new Ferdium folder
> 4. Quit ferium
> 5. Copy the "config" folder
> 6. Paste to your old folder
> 7. Delete "Ferdium" folder
> 8. Done

I met this problem too and can't solve.
Where can I find config folder?

Thanks.

**Comment by kevintaw2** [comment]
> > It works for me like this:
> > Open %AppData%
> > 
> > 1. I renamed the folder from Ferdium to ferdium_old
> > 2. Open the Ferdium App
> > 3. It will create a new Ferdium folder
> > 4. Quit ferium
> > 5. Copy the "config" folder
> > 6. Paste to your old folder
> > 7. Delete "Ferdium" folder
> > 8. Done
> 
> I met this problem too and can't solve. Where can I find config folder?
> 
> Thanks.

Here it is:
User > AppData > Roaming > Ferdium > Config

**Comment by bjab** [comment]
Small tip for everybody having such issue.
Run ferdium with logging (also works for portable version) . Run terminal/console (for windows run cmd)  and then go to ferdium install directory. Then run `ferdium --enable-logging`.
You will get console output with error log and one step closer to find out, what is happening.
In my case it showed:
`SyntaxError: c:\Users\Bartek\PortableApps\Ferdium\FerdiumAppData\FerdiumAppData\config\settings.json: Unexpected token ' ', "          "... is not valid JSON`
It turned out, that somehow my `setting.json` file was zeroed (so wasn't empty, but did not contain text)

**Comment by kngharv** [comment]
should we file a feature enhancement in which a backup settings.json file is automatically created every time ferdium is successfully launched.  And when ferdum encounter corrupted setting.json,  it automatically uses the backup settings.json.bak file?

**Comment by onchito-walks** [comment]
Confirmed that this issue still occurs on Windows with Ferdium 7.1.2.

Symptoms:

* Ferdium processes appear in Task Manager.
* No GUI or tray icon appears.
* Reinstalling Ferdium, including a forced Winget reinstall, does not resolve it.

Launching Ferdium from PowerShell exposed the actual startup error:

```text
SyntaxError: C:\Users\ray\AppData\Roaming\Ferdium\config\settings.json:
Unexpected token ... is not valid JSON
```

Ferdium was failing while hydrating its settings, before the GUI initialized. Reinstallation did not help because the installer preserved the corrupted file under `%APPDATA%\Ferdium`.

This PowerShell recovery preserved the corrupt file and allowed Ferdium to regenerate a valid settings file:

```powershell
Stop-Process -Name Ferdium -Force -ErrorAction SilentlyContinue

$exe = "$env:LOCALAPPDATA\Programs\Ferdium\Ferdium.exe"
$settings = "$env:APPDATA\Ferdium\config\settings.json"
$backup = "$settings.corrupt-$(Get-Date -Format 'yyyyMMdd-HHmmss').bak"

if (-not (Test-Path $exe)) {
    throw "Ferdium executable not found at: $exe"
}

if (Test-Path $settings) {
    Move-Item -LiteralPath $settings -Destination $backup -Force
    Write-Host "Corrupt settings file preserved at:"
    Write-Host $backup
}

Start-Process -FilePath $exe
```

Ferdium then opened normally.

The application should ideally catch malformed JSON during startup, preserve the invalid file, regenerate default settings, and display a recoverable error instead of leaving background processes running with no visible interface.

**Comment by CaptainException** [comment]
Why is this issue closed? The bug was not fixed.

I still have this bug on 7.2.0 on Win11 25H2.

And for me not only settings.json, but also proxy.json was corrupted. I had to delete both.

Trying to launch the app multiple times also does not kill the running instance. The processes will acumulate for every single invcation and block 200MB of memory each – which is its own problem besides loosing all your settings.

**Comment by Willizxy** [comment]
TBH, I gave up with Ferdium and other similar apps and made my own app
using Claude which works great.

Regards,

William Sale

**Comment by SpecialAro** [comment]
> Why is this issue closed? The bug was not fixed.
> 
> I still have this bug on 7.2.0 on Win11 25H2.
> 
> And for me not only settings.json, but also proxy.json was corrupted. I had to delete both.
> 
> Trying to launch the app multiple times also does not kill the running instance. The processes will acumulate for every single invcation and block 200MB of memory each – which is its own problem besides loosing all your settings. 

This issue is 4 years old. It was reproduced by @onchito-walks 2 months ago on version 7.1.2 (which is also a 4 month old stable).

Version 7.2.2 (the most recent stable before the current stable built 7h ago!) contained a fix for this. You are reporting this issue with 7.2.0 which, at the time of your writing, still not the most recent stable.

Please refrain from raising issues or commenting on old issues if you are not using the most recent Ferdium version - this clutters the issue box and is extremely overwhelming for me as an (almost) sole maintainer...

If this issue is still pressisting in the latest Ferdium stable, please open a new issue or DM me on discord!
